### ISSUE TITLE
big playlist download ?

### ISSUE THREAD

**Issue by mirsella** [benehmb/YoutubeDLAutoDownloader#1]
hey

have tried downloading big playlist, like +300 music ? even when adding `'cookiefile': 'cookies.txt',` to youtube_dl OPTS, i stop after like 20 videos with eror 503 forbidden because of youtube rate limiting me.

thanks

**Comment by benehmb** [comment]
I think this is because of the new YouTube-API. You could try, adding an [API-Token](https://developers.google.com/youtube/v3/).
I'm afraid, at the moment, I have no time to fix it, but if you can, feel free to do so!

~Bene

**Comment by mirsella** [comment]
thanks for the answer, i'm now using yt-dlp which downloaded everything without problems
